project:
  type: website
  output-dir: _site

website:
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    title: "Virtual Zarr examples"
    tools:
      - icon: github
        href: https://github.com/virtual-zarr/esip-2025
        text: "Repo"
    contents:
      - href: index.qmd
        text: Home
      - section: Examples
        contents:
          - href: examples/01_AWS_Public_Data_Program_NetCDF.ipynb
            text: Walk through - NetCDFs on AWS
          - href: examples/02_Earthdata_NetCDF.ipynb
            text: Hands on - NetCDFs from Earthdata
          - href: examples/03_STAC_Collection_for_Virtual_Icechunk_Store.ipynb
            text: STAC collection for virtual store
          - href: examples/04_STAC_Items_for_legacy_files_in_Virtual_Icechunk_Store.ipynb
            text: STAC items for legacy files referenced by virtual store
format:

  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
filters:
  - quarto
