[project]
name = "virtualizarr-dse-workshop"
description = "VirtualiZarr Workshop"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.11"
jupyter = ">=1.1.1,<2"
rasterio = ">=1.4.3,<2"
rioxarray = "*"
xarray = "==2025.09.0"
virtualizarr = "==2.1.2"
zarr = "==3.1.2"
ipykernel = ">=6.29.5,<7"
pip = ">=25.1.1,<26"
icechunk = ">=1.0.0,<2"
h5py = ">=3.14.0,<4"
earthaccess = ">=0.12.0,<0.13"
cftime = ">=1.6.4,<2"
jupyterlab = ">=4.4.6,<5"
xstac = ">=1.2.0,<2"
shapely = ">=2.1.1,<3"
rustac = ">=0.8.1,<0.9"

[environments]
default = { solve-group = "default" }
